# SPDX-FileCopyrightText: 2023, Yaskawa America, Inc.
# SPDX-FileCopyrightText: 2023, Delft University of Technology
#
# SPDX-License-Identifier: Apache-2.0

# empty request (service returns information about all active alarms & errors).

---

# defined result codes and strings
uint32 RC_OK=1
string STR_OK="Success"

uint32 RC_ERR_GET_ALARM_CODE_API=10
string STR_ERR_GET_ALARM_CODE_API="Could not retrieve alarm data (M+ API failure)"

uint32 RC_ERR_RETRIEVING_ALARM_INFO=15
string STR_ERR_RETRIEVING_ALARM_INFO="Could not retrieve alarm info"

uint32 RC_ERR_RETRIEVING_ERROR_INFO=20
string STR_ERR_RETRIEVING_ERROR_INFO="Could not retrieve error info"

# Result of the service invocation. Values other than one (1) signal failure.
#
# NOTE: future versions of this service may use a different set of result codes
uint32 result_code

# string representation of the value in 'result_code', for humans
string result_message

# Each entry in this list provides detailed information about all currently
# active alarms. If this list is empty, there are no active alarms.
#
# Note: order of entries in this list does not encode for any specific severity
# or priority of active alarms.
motoros2_interfaces/AlarmInfo[] alarms

# Each entry in this list provides detailed information about all currently
# active errors. If this list is empty, there are no active errors.
#
# Note: order of entries in this list does not encode for any specific severity
# or priority of active errors.
motoros2_interfaces/ErrorInfo[] errors
