# SPDX-FileCopyrightText: 2024, Yaskawa America, Inc.
# SPDX-FileCopyrightText: 2024, Delft University of Technology
#
# SPDX-License-Identifier: Apache-2.0

# empty request

---

# Result of the service invocation. Values other than one (1) signal failure.
#
# NOTE: future versions of this service may use a different set of result codes
int32 result_code

# string representation of the value in 'result_code', for humans
string message

# names of jobs on the controller, no file extensions
string[] names
